# Generated by Django 2.0.7 on 2019-02-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaltysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avregning_detaljert',
            name='antall',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='avregning_detaljert',
            name='dl_spor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='avregning_detaljert',
            name='dl_utgivelse',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='avregning_detaljert',
            name='inntekter',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='avregning_detaljert',
            name='kostnader',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='avregning_detaljert',
            name='streams',
            field=models.IntegerField(null=True),
        ),
    ]
