# Generated by Django 2.0.7 on 2019-02-11 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('royaltysystem', '0003_utgivelse_utgittdato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utgivelse',
            name='utgittdato',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
