# Generated by Django 2.0.7 on 2019-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaltysystem', '0004_auto_20190211_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utgivelseformat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
