# Generated by Django 2.0.7 on 2019-02-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royaltysystem', '0005_auto_20190211_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utgivelseformat',
            old_name='format_type',
            new_name='fysisk_format_type',
        ),
    ]
