# Generated by Django 2.0.7 on 2019-02-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaltysystem', '0007_auto_20190211_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avregning_detaljert',
            name='antall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avregning_detaljert',
            name='dl_spor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avregning_detaljert',
            name='dl_utgivelse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avregning_detaljert',
            name='inntekter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='avregning_detaljert',
            name='kostnader',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='avregning_detaljert',
            name='streams',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
