# Generated by Django 2.0.7 on 2019-02-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaltysystem', '0009_avregning_detaljert_brutto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avregning',
            name='royalty_prosent',
        ),
        migrations.AddField(
            model_name='avregning',
            name='kostnader',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='avregning',
            name='utbetalt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utgivelse',
            name='royalty_prosent',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
            preserve_default=False,
        ),
    ]
