# Generated by Django 2.0.7 on 2019-02-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royaltysystem', '0010_auto_20190217_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('periode', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('periode_start', models.DateField()),
                ('periode_slutt', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='avregning',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaltysystem.Periode'),
        ),
        migrations.AddField(
            model_name='avregning_detaljert',
            name='periode_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='royaltysystem.Periode'),
        ),
    ]
